// === wrangler.toml ===
/*
name = "scriptbuilder-mvp"
compatibility_date = "2024-01-01"

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "scriptbuilder-mvp"
database_id = "your-database-id"