# ScriptBuilder MVP - Cloudflare Pages Configuration

name = "scriptbuilder-mvp"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "."

# Environment variables (set in Cloudflare dashboard)
[vars]
# Add any public environment variables here

# Preview environment (for git branches other than main)
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "scriptbuilder-mvp"
database_id = "200262b3-1fdd-4bcb-b3d8-cf6c9a47238d"

# Production environment (for main branch)
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "scriptbuilder-mvp"
database_id = "200262b3-1fdd-4bcb-b3d8-cf6c9a47238d"